//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaveenaAccounts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NaveenaAccounts.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _05bx001 {
            get {
                object obj = ResourceManager.GetObject("05bx001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _148 {
            get {
                object obj = ResourceManager.GetObject("148", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1481 {
            get {
                object obj = ResourceManager.GetObject("1481", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Akonadi_person {
            get {
                object obj = ResourceManager.GetObject("Akonadi-person", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Akonadi_person1 {
            get {
                object obj = ResourceManager.GetObject("Akonadi-person1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Akonadi_person2 {
            get {
                object obj = ResourceManager.GetObject("Akonadi-person2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Akonadi_person3 {
            get {
                object obj = ResourceManager.GetObject("Akonadi-person3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Background {
            get {
                object obj = ResourceManager.GetObject("Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Background1 {
            get {
                object obj = ResourceManager.GetObject("Background1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BG {
            get {
                object obj = ResourceManager.GetObject("BG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BO_Organization {
            get {
                object obj = ResourceManager.GetObject("BO_Organization", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BO_Report {
            get {
                object obj = ResourceManager.GetObject("BO_Report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BO_Report1 {
            get {
                object obj = ResourceManager.GetObject("BO_Report1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BO_Role {
            get {
                object obj = ResourceManager.GetObject("BO_Role", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BO_Rules {
            get {
                object obj = ResourceManager.GetObject("BO_Rules", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_close_n {
            get {
                object obj = ResourceManager.GetObject("btn_close_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_minimize_n {
            get {
                object obj = ResourceManager.GetObject("btn_minimize_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BusinessProjectn {
            get {
                object obj = ResourceManager.GetObject("BusinessProjectn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap close_16x16 {
            get {
                object obj = ResourceManager.GetObject("close-16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Completed {
            get {
                object obj = ResourceManager.GetObject("Completed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CustomReccurence {
            get {
                object obj = ResourceManager.GetObject("CustomReccurence", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Editor_Add {
            get {
                object obj = ResourceManager.GetObject("Editor_Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Editor_Edit {
            get {
                object obj = ResourceManager.GetObject("Editor_Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Information {
            get {
                object obj = ResourceManager.GetObject("Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Invalid {
            get {
                object obj = ResourceManager.GetObject("Invalid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap keys_16x16 {
            get {
                object obj = ResourceManager.GetObject("keys-16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuBar_AboutInfo {
            get {
                object obj = ResourceManager.GetObject("MenuBar_AboutInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuBar_Edit {
            get {
                object obj = ResourceManager.GetObject("MenuBar_Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuBar_Export {
            get {
                object obj = ResourceManager.GetObject("MenuBar_Export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuBar_Export1 {
            get {
                object obj = ResourceManager.GetObject("MenuBar_Export1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuBar_Export2 {
            get {
                object obj = ResourceManager.GetObject("MenuBar_Export2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuBar_FindObjectByID {
            get {
                object obj = ResourceManager.GetObject("MenuBar_FindObjectByID", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuBar_Link {
            get {
                object obj = ResourceManager.GetObject("MenuBar_Link", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuBar_Next {
            get {
                object obj = ResourceManager.GetObject("MenuBar_Next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuBar_Next1 {
            get {
                object obj = ResourceManager.GetObject("MenuBar_Next1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuBar_Open {
            get {
                object obj = ResourceManager.GetObject("MenuBar_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuBar_Prev {
            get {
                object obj = ResourceManager.GetObject("MenuBar_Prev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuBar_Print {
            get {
                object obj = ResourceManager.GetObject("MenuBar_Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuBar_Validate {
            get {
                object obj = ResourceManager.GetObject("MenuBar_Validate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navBarIcons_copy {
            get {
                object obj = ResourceManager.GetObject("navBarIcons-copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navBarIcons_copy1 {
            get {
                object obj = ResourceManager.GetObject("navBarIcons-copy1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap parcel {
            get {
                object obj = ResourceManager.GetObject("parcel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap password1 {
            get {
                object obj = ResourceManager.GetObject("password1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap richeditdemoicons___Copy {
            get {
                object obj = ResourceManager.GetObject("richeditdemoicons - Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap richeditdemoicons___Copy___Copy {
            get {
                object obj = ResourceManager.GetObject("richeditdemoicons - Copy - Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SlideshowCloseOrangeg {
            get {
                object obj = ResourceManager.GetObject("SlideshowCloseOrangeg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Valid {
            get {
                object obj = ResourceManager.GetObject("Valid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
